### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Github-User-632345** [RequiDev/ReModCE#10]
Texture decimation for performance but only effect worlds and avatars, not the VRC menus and nameplates.

**Comment by FenrixTheFox** [comment]
This isn't possible quickly reading the Unity docs Decimation can only be global using masterTextureLimit 
[https://docs.unity3d.com/ScriptReference/QualitySettings-masterTextureLimit.html](https://docs.unity3d.com/ScriptReference/QualitySettings-masterTextureLimit.html)
