### ISSUE TITLE
[Bug] Cannot Use "Switch Avatar" button when ReModCE Avatar Favorites are turned off. 

### ISSUE THREAD

**Issue by forever-and-a-day** [RequiDev/ReModCE#13]
No avatar switching will work, either from different mods or from the stock favs/vrc+ favs, unless ReModCE's Avatar favorites is turned on. When disabled, attempting to switch avatars will fail (the main menu stays open and nothing happens). Nothing is logged to the melonloader console after this action, but the following can be found in VRChat's output logs that may be usefull:
```
2021.10.23 23:49:29 Log        -  [AssetBundleDownloadManager] Unpacking Download


2021.10.23 23:49:29 Warning    -  The referenced script (Unknown) on this Behaviour is missing!



2021.10.23 23:49:29 Warning    -  The referenced script on this Behaviour (Game Object 'prefab-id-v1_avtr_2a79a39b-8be7-4717-af7e-07fd7afa17c1_2369439933') is missing!



2021.10.23 23:49:29 Warning    -  The referenced script (PipelineSaver) on this Behaviour is missing!



2021.10.23 23:49:29 Warning    -  The referenced script on this Behaviour (Game Object 'prefab-id-v1_avtr_2a79a39b-8be7-4717-af7e-07fd7afa17c1_2369439933') is missing!



2021.10.23 23:49:29 Warning    -  The referenced script on this Behaviour (Game Object 'prefab-id-v1_avtr_2a79a39b-8be7-4717-af7e-07fd7afa17c1_2369439933') is missing!
```
Note that when the game is initially loaded, ReModCE's "favorite" button above the avatar preview is visible and will favorite avatars despite favorites being turned off. It will disappear for the duration of the game session if favorites are toggled on and back off, but this will not fix the problem with avatar switching, which will remain non-functional until ReModCE's favorites are turned back on. 
Let me know if you need any more info. Thanks! :D

**Comment by RequiDev** [comment]
Is this still an issue?
