### ISSUE TITLE
Ah, no buttons

### ISSUE THREAD

**Issue by Hacker1254** [RequiDev/ReModCE#16]
`Main Menu`
![image](https://user-images.githubusercontent.com/69991448/140948180-acb3af98-f4d4-4660-86f1-ddaed1c4224a.png)
`Sub Menu`
![image](https://user-images.githubusercontent.com/69991448/140948009-b66d5bd1-67d1-4262-ba6b-3900355c4fa3.png)
the visuals shows the wireframe submenu, but no buttons or toggles within that
Let me know if you need more info

**Comment by RequiDev** [comment]
Any errors in your logs?

**Comment by Hacker1254** [comment]
1 moment ill check
its full of errors from other mods, ill check if its a conflit

**Comment by Hacker1254** [comment]
![image](https://user-images.githubusercontent.com/69991448/140948973-ddd17c0d-36fe-463e-889c-c08b0c348bda.png)

**Comment by Hacker1254** [comment]
anyupdates?

**Comment by RequiDev** [comment]
Try reinstalling MelonLoader.

**Comment by Hacker1254** [comment]
is it working for you?

**Comment by RequiDev** [comment]
Yes, it's working fine for me.

**Comment by Hacker1254** [comment]
Damn, i guess this is my side

**Comment by Hacker1254** [comment]
Uh wait, are you using steam?

**Comment by Hacker1254** [comment]
ah, thats my issue
i used ocu link

**Comment by Hacker1254** [comment]
when are you planning to re~add ocu support?
