### ISSUE TITLE
ReModCE not working (buttons missing) (Steam Version)

### ISSUE THREAD

**Issue by danielallencoates** [RequiDev/ReModCE#17]
ReModCE is not working on my end despite my multiple attempts to get it running, and I have run out of things to try
re-installed melonloader (re-install button, and also uninstall + install)
using the command "--melonloader.agfregenerate"
Verifying Files, ETC.
![1](https://user-images.githubusercontent.com/7468265/141139955-00efee5d-a1d2-4a58-acee-3f6001fa1d90.png)
![2](https://user-images.githubusercontent.com/7468265/141139968-b225fda5-8ced-40b9-81b6-128e3960a9cc.png)
![sdgfasdfasdf](https://user-images.githubusercontent.com/7468265/141139984-46808502-ea45-4068-8a9f-b3c80b334118.png)

[Latest.log](https://github.com/RequiDev/ReModCE/files/7513781/Latest.log)

(P.S sorry if this is sloppy, this is my first time using Github)

**Comment by RequiDev** [comment]
I just pushed an update that should take care of that problem. Can you try again and see if it works now?

**Comment by Hacker1254** [comment]
Sure

**Comment by danielallencoates** [comment]
Partially working now, but some buttons still seem to be missing?
Noclip, Flight Speed, entire Dynamic bones section
And pressing the wireframe settings button crashes the game
![Movement](https://user-images.githubusercontent.com/7468265/141146169-4898146c-6200-48df-9808-376cd336e098.png)
![Visuals](https://user-images.githubusercontent.com/7468265/141146187-82480595-d9fa-46e0-9e37-c68e53a2d53f.png)
![DYNAMIC](https://user-images.githubusercontent.com/7468265/141146201-84d165ed-ac36-4516-801f-c57c93f452a5.png)
![ERROR](https://user-images.githubusercontent.com/7468265/141146252-5ba71b2e-1622-414d-9082-51191e33651b.png)
[Latest.log](https://github.com/RequiDev/ReModCE/files/7514071/Latest.log)

**Comment by danielallencoates** [comment]
Sorry if I'm not too great at this by the way

**Comment by danielallencoates** [comment]
Okay, so I found the issue on my end, sorry if I wasted your time, apparently MelonLoaderInstaller.exe was not grabbing all necessary Dependencies, don't know why, but using the Zip version fixed it.

**Comment by RequiDev** [comment]
I'm pretty sure your issue is caused by "AttachToPlayer" by Stellar. The way he implements ReMod.Core (my VRChat library) that ReModCE relies on is wrong.

**Comment by danielallencoates** [comment]
that fixed it

**Comment by spike24** [comment]
i have the same problem
