### ISSUE TITLE
[Issue] OnUiManagerInit gets called very late

### ISSUE THREAD

**Issue by Jdbye** [RequiDev/ReModCE#18]
I'll prefix this by saying that it might not be causing issues right now but as you make changes or extend the functionality of the mod you will likely run into this issue, as I did while I was trying to fix FlyComponent (it seems very buggy for me for some reason, maybe it's something I did so I was trying to fix it, but eh I digress) and noticed my OnPlayerJoined code was never triggering.
So it's not quite a bug, and not something that needs changing right away, just consider it an improvement.
That issue being, OnUiManagerInit (late) only gets called once the quick menu is opened, because Object.FindObjectOfType (in WaitForUiManager) only returns *active* GameObjects.
As InitializeNetworkManager is called there, the network manager also gets called late which means OnPlayerJoined/OnPlayerLeft events can be dropped which could manifest in strange ways. Especially if you want it to trigger when the *local* player joins, as it won't in the original code.

However, OnUiManagerInit (late) is not really needed. Anything in OnUiManagerInit can be moved to OnSceneWasLoaded.
Rather than moving everything and renaming methods in multiple places I did it the easier way:

```
        public override void OnSceneWasLoaded(int buildIndex, string sceneName)
        {
            if (buildIndex == 2) OnUiManagerInit();

            foreach (var m in Components)
            {
                m.OnSceneWasLoaded(buildIndex, sceneName);
            }
        }
```

And added a check in OnUiManagerInit itself just to make sure doesn't run more than once:

```
        public void OnUiManagerInit()
        {
            if (initialized) return;

            ReLogger.Msg("Initializing UI...");

            ...

            initialized = true;
        }
```

InitializeNetworkManager should be called as early as possible to make sure OnPlayerJoined/OnPlayerLeft always get called. Easiest to do by using a coroutine:

```
        public override void OnApplicationStart()
        {
            ...

            MelonCoroutines.Start(WaitForNetworkManager());
        }

        private IEnumerator WaitForNetworkManager()
        {
            while (ReferenceEquals(NetworkManager.field_Internal_Static_NetworkManager_0, null)) yield return null;
            InitializeNetworkManager();
        }
```
Credit where credit is due, I borrowed that part from knah's mods.

There are a few caveats however:
- In many cases, you can't use GameObject.Find/Object.FindObjectOfType anymore as they only find *active* GameObjects. Later Unity versions take a bool includeinactive parameter but it doesn't exist in 2019.
- You can't use QuickMenu.field_Protected_MenuStateController_0. It's not set until the menu is opened.
- In some instances .GetComponentInChildren/.GetComponentsInChildren() may need a "true" parameter added to find inactive components. I changed it on some without really testing if it was necessary so I left the rest alone and it's working fine so maybe it's not needed. If you get null reference exceptions this is a likely cause.

These have relatively simple solutions by modifying QuickMenuEx.cs changing _quickMenuInstance = ... as well as MenuStateCtrl.

There is no need to use field_Protected_MenuStateController_0 since the MenuStateController is literally on the same GameObject, so that's an easy fix.

As for finding objects without using Object.Find, I locate the full path of the GameObject I'm looking for (or the parent GameObject of a Component as in this case) and use Transform.Find as below. UserInterface appears to always be active and Transform.Find will return inactive objects, so this works for retrieving any UI object no matter their state (in my testing so far), this is the way I do it in other mods, where I already use OnSceneWasLoaded for UI stuff.
I will say I didn't exactly come up with this, I saw other mods doing it this way although I didn't understand why until I ran into issues with UI stuff doing it another way. But this seems to be the most reliable/failsafe way of doing it.

```
        public static VRC.UI.Elements.QuickMenu Instance
        {
            get
            {
                if (_quickMenuInstance == null)
                {
                    _quickMenuInstance = UnityEngine.GameObject.Find("UserInterface").transform.Find("Canvas_QuickMenu(Clone)").GetComponent<VRC.UI.Elements.QuickMenu>();
                    if (_quickMenuInstance == null) MelonLogger.Error("QuickMenu is null"); // this didn't trigger even once, but I added it to troubleshoot MenuStateCtrl giving a null reference exception (which I fixed)
                }
                return _quickMenuInstance;
            }
        }

        public static MenuStateController MenuStateCtrl => Instance.GetComponent<MenuStateController>();
```

It's possible I've forgotten some other changes I made because I made so many changes trying to fix the errors caused by just moving OnUiManagerInit/InitializeNetworkManager and changing nothing else and I'm not sure if I reverted all of them. But these are the main ones that took me a while to figure out.

**Comment by RequiDev** [comment]
This was an oversight on my part when preparing the mod for the UI update. This should be fixed in the latest commit.
