### ISSUE TITLE
issue with not choosing to search with emmvrc or remodce

### ISSUE THREAD

**Issue by thecourierhunter** [RequiDev/ReModCE#23]
so when i try to search for avatars. it usually have a popup of what to search with but sometimes it broke and only use the remodce search.  it seems to happen instantly when i use the emmvrc function on a profile to see author's avatar

**Comment by RequiDev** [comment]
emmVRC probably changed how the override the search box when they updated for the UI update. I'll talk with one of the developers to find out how to fix this.

**Comment by thecourierhunter** [comment]
just want to check in to ask about the progress of the fix if you don't mind me asking

**Comment by RequiDev** [comment]
Do you have a decent way of reproducing that problem?

**Comment by thecourierhunter** [comment]
from what i've done to recreate the problem is when i search an avatar. i go to avatar details, click on avatar author, then on the profile, i've clicked emmvrcfuction to use the search avatar button and bam. the popup no longer shows up whenever i search

**Comment by thecourierhunter** [comment]
just to let you know if there's any mod conflicts, no i've removed other mods besides emm and remod just to double check and it still broke for me. i could do more testing to see if there's other ways to reproduce the problem besides the one i've mentioned in my previous comment if you think the one i've updated you on isn't decent enough.

**Comment by RequiDev** [comment]
I pushed an update a few days ago. Is this still a problem?

**Comment by thecourierhunter** [comment]
Sorry for the month response! seems like your update fixed it! no issue so far!

**Comment by RequiDev** [comment]
Perfect. That's how I like it!
