### ISSUE TITLE
Searching Problem

### ISSUE THREAD

**Issue by ItIsWaka** [RequiDev/ReModCE#28]
Everytime I try to search an avatar [after like 10 minutes of playing the game] with the search feature, nothing happens, the avatar that I searched for doesn't appear.
Maybe the problem is that I use emmVRC and ReMod at the same time and they are not compatible in some ways? But every time it happens I just need to restart the game and it works fine.

**Comment by RequiDev** [comment]
The ReModCE API was offline for server maintenance earlier today for like 6 hours. Are you sure you're not referring to that?
If not:
Does the search work when you use it initially? Are there any errors in your MelonLoader console/log?

**Comment by ItIsWaka** [comment]
No the problem wasn't for the maintenance, yesterday it did the same thing
Everything works fine in the first 10 minutes of playing, but after sometime, it stops working, I've never seen an error in the log, next time I play VRChat I'll look into it and add it in a future comment if I find anything

**Comment by RequiDev** [comment]
Is this still a problem?
