### ISSUE TITLE
So for some reason all of the features are missing and i dont know why

### ISSUE THREAD

**Issue by Jake1214** [RequiDev/ReModCE#33]
On the ReModCE menu nothing is showing up in the sub menus
![Screenshot 2022-01-30 205101](https://user-images.githubusercontent.com/98721863/151728680-4fa22ade-871c-4dfc-8673-47a71da16925.png) (This All shows up)
But when I go on any submenu
![Screenshot 2022-01-30 205129](https://user-images.githubusercontent.com/98721863/151728728-310abf8a-6d74-4efe-b3d3-c0a73d43f720.png)
![Screenshot 2022-01-30 205143](https://user-images.githubusercontent.com/98721863/151728733-f9a97157-b520-4c9b-acd7-fc74d3c6312c.png)
![Screenshot 2022-01-30 205158](https://user-images.githubusercontent.com/98721863/151728736-924a6660-b94d-434b-9b6c-ebcc6c264ae5.png)
I don't know why this is happening.

**Comment by RequiDev** [comment]
There are probably errors in your MelonLoader log. Can you post it?

**Comment by Jake1214** [comment]
![Screenshot 2022-01-30 205640](https://user-images.githubusercontent.com/98721863/151728994-1e1135b2-7784-4a9f-bcfb-3746dc159793.png)

**Comment by Jake1214** [comment]
There is a lot of issues

**Comment by RequiDev** [comment]
You seem to be running ReModCE on the Oculus version of VRChat. At the moment I can't support both Steam and Oculus. You'll have to use the Steam version.

**Comment by Jake1214** [comment]
Oh ok thankyou
