### ISSUE TITLE
pin wont work, dont understand how to use forgot/reset pin website?

### ISSUE THREAD

**Issue by kittyy4045** [RequiDev/ReModCE#34]
im not sure what im supposed to enter for the ID when i go to the reset website, all i could think of using was my vrchat username and it didnt work >_> not sure what to do please help ^___^

**Comment by RequiDev** [comment]
To reset your PIN enter your user id. It should give you further instructions shortly after.

**Comment by kittyy4045** [comment]
> 

i just dont understand what the user id is ^__^ my vrchat username wont work? aaa sorry if this seems dumb i just really dont understand when i put in my vr user it says this user doesnt exist, am i supposed to be using something else? ^_^

**Comment by RequiDev** [comment]
If you open the VRChat website and click on your profile, the URL will contain your user id.
It starts with usr_

**Comment by kittyy4045** [comment]
> If you open the VRChat website and click on your profile, the URL will contain your user id. It starts with usr_

aaa it finally works again!!! thankyou so so much!!! :D
