### ISSUE TITLE
[Bug]: cant compile (where are the references, and/or how would i acquire them?)

### ISSUE THREAD

**Issue by salt431** [RequiDev/ReModCE#38]
**Describe the bug**

this client will not compile in vscode without the reference files, which are not included in the repository, nor are there any directions on how to acquire them, ive spent hours searching for the dlls to compile this, as ive made changes to the code for the UI elements that i have personalized for myself, however the missing dlls kinda get in the way of me being able to test and use the fork ive made

/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Assembly-CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Il2Cppmscorlib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnhollowerBaseLib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine.CoreModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "VRC.UI.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "VRC.UI.Elements". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "VRC.UI.Shared". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]
/snap/dotnet-sdk/158/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "VRC.Utility". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/haxer/RiderProjects/ReModCE/ReModCE.Loader/ReModCE.Loader.csproj]

i have managed to get the melonloader dll myself, but can you please either include the reference dlls or at least point us somehow to acquire them?

**Comment by RinLovesYou** [comment]
There are so many things wrong here

A: you're using .net core. Read up on mono and how to install it on Linux so you can use the dotnet framework.

B: you talk about vscode yet there are Rider paths in your logs. Please use rider if you have it, it has a great integration with mono.

C: to answer your question, reference assemblies are located in /Melonloader/Managed/

This is not a bug, but a general lack of understanding of the tools you need in order to use it, please read up on the [wiki](https://melonwiki.xyz) and maybe create a mod yourself as a sanity check, before trying to contribute to a project

**Comment by RequiDev** [comment]
And to add what Rin said:
Looking at the changes in your fork. Fuck off.

**Comment by KeafyIsHere** [comment]
https://user-images.githubusercontent.com/58978401/158492540-2945d53d-f913-4b07-b627-10dc2822a15c.mp4

This you
