### ISSUE TITLE
Issue with not changing into avatars or favoriting when clicking on them.

### ISSUE THREAD

**Issue by GibbsVR** [RequiDev/ReModCE#39]
When clicking ton an avatar I search for it doesn't let me change into or favorite it.

1. Go to 'Avatars'
3. Click on 'Search'
4. Click any avatar
5. Try to favorite or change into it
6. Nothing happens
**Expected behavior**
I would change into the avatar and it would be added to my favorites list.

**Comment by RequiDev** [comment]
Any errors in your MelonLoader log?

**Comment by GibbsVR** [comment]
nope

**Comment by GibbsVR** [comment]
[MelonLoader_22-03-19_15-32-43.099.log](https://github.com/RequiDev/ReModCE/files/8309993/MelonLoader_22-03-19_15-32-43.099.log)

**Comment by GibbsVR** [comment]
would it be because i'm not playing in vr mode?

**Comment by ValliteKing** [comment]
Yeah, I'm having this issue too. Although, I click it and my profile image does change to the avatar I selected. But reloading the world or restarting the game reverts it back.

**Comment by RequiDev** [comment]
The avatar may be deleted or private now and you won't be able to switch into it.
