### ISSUE TITLE
[Bug]: Can't search up avatars, and won't let me enter a pin. ( VRChat )

### ISSUE THREAD

**Issue by FluffyCuteCandy** [RequiDev/ReModCE#41]
**Describe the bug**
When looking up for an avatar in VRChat and selecting REMod CE as an option, it says that I needed to log in using a pin even though I never needed one or have created one prior, so when I went to my avatar settings as instructed and entered a pin that I would normally use it said it was invalid and now I can't search for avatars at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go and look up new avatar in VRChat
2. Responds with 'Unavailable due to no set pin'
3. Try to reset and enter new pin in avatar settings of REModCE
4. Responds with incorrect pin, even with pins set previously,

**Expected behaviour**
To have a reset pin and to have access to search up avatars again.

**Screenshots/Logs**
![2022-03-28](https://user-images.githubusercontent.com/102492234/160306820-32f22ef2-32d6-4cc4-b561-14c49dff300b.png)
![2022-03-28 (1)](https://user-images.githubusercontent.com/102492234/160306824-e44157eb-adb8-4cbe-9bfe-2c6eff1d5218.png)

**Comment by RequiDev** [comment]
https://github.com/RequiDev/ReModCE#forgot-your-pin
