### ISSUE TITLE
[Bug]: REmodCE Not working at all.

### ISSUE THREAD

**Issue by EmberFlames** [RequiDev/ReModCE#43]
So, when I install Remod and watch over the bootup, Remod will not activate at all. I have the DLL in the right place, but wont boot up. Or having a issue with creating a entity. I cant tell from the error code.
![Screenshot (50)](https://user-images.githubusercontent.com/68975624/161619809-9a89eb77-9922-4218-97c0-7837eaba33dd.png)

**Comment by Kiokuu** [comment]
Update MelonLoader to v0.5.3+
Refer to: "You need at least MelonLoader v0.5.3 since VRChat Build 1169!"

**Comment by EmberFlames** [comment]
How do I update. Bear with me and my noobishness

**Comment by RequiDev** [comment]
https://github.com/LavaGang/MelonLoader#how-to-use-the-installer

**Comment by EmberFlames** [comment]
Thanks!
