### ISSUE TITLE
[Bug]: Compatibility Clashing

### ISSUE THREAD

**Issue by GithubPremiumPlan** [RequiDev/ReModCE#44]
Mod has clashing with Component Toggle

When enabling chair toggle (and other toggles that would eventually be added) it overrides each other

Please add compatibility with component toggle mod by making Remod component toggles disabled completely if Component toggle is detected.

**Comment by RequiDev** [comment]
https://github.com/RequiDev/ReModCE/commit/019aed4f24ef210b5bad2dfae0f6701e63c79b02
