### ISSUE TITLE
ReModCE doesen't show up in VRchat [Bug]: 

### ISSUE THREAD

**Issue by Josva08** [RequiDev/ReModCE#45]
**Describe the bug**
The mod doesn't show up in VRChat. Worked just fine earlier today. But when I restarted the game later on the mod disappeared. 

**To Reproduce**
Just starting VRChat does it for me.

**Expected behavior**
I don't remember any differences from normal behavior. But the ReMod tab in the VRChat tablet menu is not there.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/74794046/164563592-676864a7-9e1f-4960-8ca1-e30265bf4e0b.png)
![image](https://user-images.githubusercontent.com/74794046/164564219-2a56afd1-9525-4db4-b0a1-e54831d602de.png)
I guess you can see my other installed mods in the console screenshot.
I tried keeping my essential mods, as they are useful and help improve performance. 

I'm new to Github, and this is my first bug report. So I hope that the information I've given can help troubleshoot this bug.

**Comment by RequiDev** [comment]
VRChat updated. Either update or reinstall your MelonLoader.

**Comment by Josva08** [comment]
That worked. I wonder why it didn't work when I used the re-install melon loader. But it worked when I uninstalled it and reinstalled it. But it works now. Thanks for the help :)
