### ISSUE TITLE
[Bug]: Issue with the avatar history not working when opening Vrchat

### ISSUE THREAD

**Issue by Typicalboy** [RequiDev/ReModCE#47]
**Describe the bug**
When going on vtchat the avatar history always crashes no matter how many times you restart the game

**Comment by RequiDev** [comment]
Delete your recent_avatars.bin in your UserData/ReModCE directory.

**Comment by Typicalboy** [comment]
> 

I'm fairly new with the mod and its workings so I may need someone to help me out with it

**Comment by RequiDev** [comment]
1. Go to your VRChat directory.
2. Go to the UserData directory. 
3. Go to the ReModCE directory.
4. Delete the recent_avatars.bin file.

**Comment by Typicalboy** [comment]
> 1. Go to your VRChat directory.
> 2. Go to the UserData directory.
> 3. Go to the ReModCE directory.
> 4. Delete the recent_avatars.bin file.

Really appreciate it bro thanks
