### ISSUE TITLE
[Bug]: Cursor will not lock onto the game when it is in focus 

### ISSUE THREAD

**Issue by imBigo** [RequiDev/ReModCE#49]
**Describe the bug**
While the game is in full screen and focused, the cursor will continue to other monitors.

**To Reproduce**
1. Play the game in desktop mode with multiple monitors.
2. Move mouse around.
3. Wait for the cursor to get on other monitors.

**Expected behavior**
Cursor to stay locked in the game.

**Additional context**
Sometimes takes a little time to happen but will keep happening.

**Comment by RequiDev** [comment]
Are you sure it's caused by ReModCE?

**Comment by imBigo** [comment]
> 

I'm not 100% sure but I have tried with the default mods that comes with VRChat Melon Assistant and all of the Safety & Security mods except Safety-Presets and the bug was happening.

**Comment by imBigo** [comment]
It seems the issue is not to do with ReModCE itself but could be other mods.
