### ISSUE TITLE
no buttons showing up when i open the REModCE tab in vr chat[Bug]: 

### ISSUE THREAD

**Issue by spike24** [RequiDev/ReModCE#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots/logs to help explain your problem.

**Additional context**

**Comment by cokp7ghgh** [comment]
same deal

**Comment by cokp7ghgh** [comment]
![Capture](https://user-images.githubusercontent.com/106300570/170430704-8ff05abf-5c7a-45cc-bcb6-66a83e78f418.PNG)

**Comment by cokp7ghgh** [comment]
my game was reinstalled and clean so i think its an update

**Comment by cokp7ghgh** [comment]
you go to the menu of remodce of vrchat / search avater menu does not work ethier nor side bar thus errors

> 

you go to the menu of remodce of vrchat / search avater menu does not work ethier nor side bar thus errors

**Comment by cokp7ghgh** [comment]
![Capture](https://user-images.githubusercontent.com/106300570/170432801-a923d78d-775e-4f87-9994-4a2b9700b18d.PNG)
![Captusre](https://user-images.githubusercontent.com/106300570/170432803-aa086de8-2f85-4b05-bb56-0ae345fef659.PNG)

**Comment by cokp7ghgh** [comment]
not able to search

**Comment by spike24** [comment]
i think its this update. same exact problem as you.

**Comment by cxaiverb** [comment]
The game updated. Requi was asleep when it did, he has since woken up and updated ReModCE. Please try removing your ReMod.core and running the game again.

**Comment by spike24** [comment]
ill try that now thanks!
