### ISSUE TITLE
[Bug]: AvatarSearchEnabled is disabled but UI elements still appear in avatars menu.

### ISSUE THREAD

**Issue by lanes10000** [RequiDev/ReModCE#58]
Bug description:
AvatarSearchEnabled is disabled but the UI element still shows in the avatars menu.

1. Go to main menu\mod settings\
2. Scroll to ReModCE
3. Disable AvatarSearchEnabled
4. Restart game
5. Reproduced

Expected behaviour
The search UI elements should no longer be present on the avatar menu

Screenshots
![image](https://user-images.githubusercontent.com/90541616/172550134-65f14dbc-640a-44ba-a6db-475bb240888d.png)
![image](https://user-images.githubusercontent.com/90541616/172550295-e1ed263a-bb3a-4ca6-bb2f-523e34b6a1ba.png)

**Comment by RequiDev** [comment]
Those options aren't meant to be used. Use the ones inside the ReModCE tab.
