### ISSUE TITLE
[Feature]: Change "Now Playing" popup UI element location to bottom or top of player FOV

### ISSUE THREAD

**Issue by lanes10000** [RequiDev/ReModCE#59]
Problem:
It's frustrating when songs transition and the UI popup is directly in the center of my field of vision.

Possible solution:
UI for songs should be located towards the bottom or top of the player's FOV.

**Comment by RequiDev** [comment]
You're able to adjust the notification system stuff using UIExpansionKit under the ReMod.Core section in Mod Settings.
