### ISSUE TITLE
[Problem]: Problems finding User ID's.

### ISSUE THREAD

**Issue by Will0m** [RequiDev/ReModCE#61]
Hello! Unfortunately, I've been attempting to receive and reset my Pin whilst VRC modding, however when attempting to reset, it asked me to input a "User ID." And because I've never done this in my life, I've got not even 1 idea where to find it. If I'm being over dramatic and am just blind, it would be appreciated to let me know. Thanks!
![image](https://user-images.githubusercontent.com/107156648/172734220-9d8d767d-9b80-47e0-a9f8-3d199e6b2c9d.png)

**Comment by RequiDev** [comment]
1) Locate the Here Tab ingame and click it. This is the tab with the icon of a marker
![](https://cdn.discordapp.com/attachments/982721463985524826/982730510755323934/unknown.png)

2) Locate yourself in the Users category and click yourself.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730574110273646/unknown.png)
3) Click the "Copy User ID" button. This will copy the ID we need to reset your pin into your clipboard.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730628980162560/unknown.png)
4) In any browser, go to this URL: https://remod-ce.requi.dev/api/pin.php (step 4)
5) Paste your user ID you copied earlier into the text box. Ctrl+V or right-click paste (step 5)
6) Click the Submit button (step 6)
![](https://cdn.discordapp.com/attachments/982721463985524826/982730745997033492/unknown.png)
7) If you followed the last steps, you should get a screen like this.
     Ensure that you see a random code surrounded by quotation marks.

     Copy the code. An example generated code is " eBCsTBI854U9WjxM " You will need this.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730836732436621/unknown.png)

8) In VRChat, At the same place you clicked "Copy User ID", 
     Click this button to open your VRChat social page.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730891791056906/unknown.png)
9) Click the Edit Bio button in your Social Page.
![](https://cdn.discordapp.com/attachments/982721463985524826/982731044329513020/unknown.png)
10) Paste the code you copied earlier anywhere in your VRChat bio. Make sure it is whole.
       Then, click the OK button.
![](https://cdn.discordapp.com/attachments/982721463985524826/982731113552285746/unknown.png)
11) Repeat steps 4, 5 and 6. Upon re-entering your user id and clicking submit, your pin should be reset.
![](https://cdn.discordapp.com/attachments/982721463985524826/982731482751713410/unknown.png)
