### ISSUE TITLE
Search isn't working for avatars[Bug]: 

### ISSUE THREAD

**Issue by phe0nx** [RequiDev/ReModCE#64]
**Describe the bug**
I go to search in avatars and it won't bring up the menu to search. However I downloaded it yesterday and it worked just fine, no problems.
**To Reproduce**
1. Go to 'avatars'
2. Click on 'search'
3. Scroll down to 'ends here'

**Expected behavior**
I expected to be able to search avatars with no problem I have tried fixing it myself but nothing super in depth.
**Screenshots/Logs**
If applicable, add screenshots/logs to help explain your problem.

**Additional context**
It worked yesterday.

**Comment by RequiDev** [comment]
I just pushed an update that hopefully addresses it.
