### ISSUE TITLE
[Bug]: Pin can't be reset

### ISSUE THREAD

**Issue by u-Kotovsky** [RequiDev/ReModCE#66]
**Describe the bug**
Can't reset my pin, returns 'This user doesn't exist'

**To Reproduce**
1. Go to ['reset pin page'](https://remod-ce.requi.dev/api/pin.php)
2. Put user id in text input
3. Click submit input

**Expected behavior**
Reset pin

**Screenshots/Logs**
![screenshot](https://user-images.githubusercontent.com/67106105/176095615-54483aef-a182-40c4-bf28-fcb650d71523.png)

**Additional context**
I have tried to use user id without 'usr_' and with it, returns same result 'This user doesn't exist'

**Comment by RequiDev** [comment]
1) Locate the Here Tab ingame and click it. This is the tab with the icon of a marker
![](https://cdn.discordapp.com/attachments/982721463985524826/982730510755323934/unknown.png)

2) Locate yourself in the Users category and click yourself.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730574110273646/unknown.png)
3) Click the "Copy User ID" button. This will copy the ID we need to reset your pin into your clipboard.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730628980162560/unknown.png)
4) In any browser, go to this URL: https://remod-ce.requi.dev/api/pin.php (step 4)
5) Paste your user ID you copied earlier into the text box. Ctrl+V or right-click paste (step 5)
6) Click the Submit button (step 6)
![](https://cdn.discordapp.com/attachments/982721463985524826/982730745997033492/unknown.png)
7) If you followed the last steps, you should get a screen like this.
     Ensure that you see a random code surrounded by quotation marks.

     Copy the code. An example generated code is " eBCsTBI854U9WjxM " You will need this.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730836732436621/unknown.png)

8) In VRChat, At the same place you clicked "Copy User ID", 
     Click this button to open your VRChat social page.
![](https://cdn.discordapp.com/attachments/982721463985524826/982730891791056906/unknown.png)
9) Click the Edit Bio button in your Social Page.
![](https://cdn.discordapp.com/attachments/982721463985524826/982731044329513020/unknown.png)
10) Paste the code you copied earlier anywhere in your VRChat bio. Make sure it is whole.
       Then, click the OK button.
![](https://cdn.discordapp.com/attachments/982721463985524826/982731113552285746/unknown.png)
11) Repeat steps 4, 5 and 6. Upon re-entering your user id and clicking submit, your pin should be reset.
![](https://cdn.discordapp.com/attachments/982721463985524826/982731482751713410/unknown.png)

**Comment by u-Kotovsky** [comment]
I did all as you said but I'm stuck at 7 step where site returns 'This user doesn't exist'
![image](https://user-images.githubusercontent.com/67106105/176097741-44ee2f1f-73f8-4d7d-80c6-8aacffb2602d.png)
![image](https://user-images.githubusercontent.com/67106105/176097789-ec649235-acd9-4403-8d33-885da739a330.png)

**Comment by BLANKE1** [comment]
If that happens, then you don't have a pin set correctly.

**Comment by u-Kotovsky** [comment]
> If that happens, then you don't have a pin set currently, you can set a pin by entering one in the "Set pin" button within the avatars submenu in the ReModCE tab.

I need to get pin, I don't have it

**Comment by RequiDev** [comment]
Then you don't reset it. You just set one ingame.

**Comment by u-Kotovsky** [comment]
> Then you don't reset it. You just set one ingame.

Just set my in-game pin as random symbols?

**Comment by BLANKE1** [comment]
Just type a set of numbers that you remember, it's a password

**Comment by u-Kotovsky** [comment]
> Just type a set of numbers that you remember, it's a password

Okay, I set my pin, so I need to wait when server will see that I have set my pin?

**Comment by BLANKE1** [comment]
No, you can just search avatars right after setting the pin.

**Comment by u-Kotovsky** [comment]
> No, you can just search avatars right after setting the pin.

Looks like I can't, returns error that I should set pin, maybe need to restart client

**Comment by u-Kotovsky** [comment]
Still getting error that I should set my pin, same result after entering my pin again

**Console error:**
[08:25:43.303] [ReModCE] [ERROR] Could not search for avatars: "You can't search avatars without having set a pin or being logged in with your pin.
        You can set a pin by opening your QuickMenu and clicking on ReModCE.
        In there you will find the "Avatars" submenu in which you can set or enter your pin."

**Comment by u-Kotovsky** [comment]
Oh Its just not reading very long pin, just no message about that, thanks you for helping guys!
