### ISSUE TITLE
Entirely malicious

### ISSUE THREAD

**Issue by HartLeeKonnor** [RequiDev/ReModCE#9]
Creates a list of people suspected of ripping and alerts user of suspected persons location in world. TOS breaking much?

**Comment by RequiDev** [comment]
Can you elaborate?

**Comment by FenrixTheFox** [comment]
As Requi said, please elaborate? ReModCE has no such features as far as we're aware.

**Comment by HartLeeKonnor** [comment]
Yes, you do. no need to lie.
My friend uses it and told me so.

**Comment by RequiDev** [comment]
ReModCE is entirely open-source. Where in the source code is that functionality that you're speaking of?

**Comment by Github-User-632345** [comment]
The private version of this mod has ripper detection and alerts not this one. Ripping is never ok, only reason you're defending it is you got caught.

**Comment by HartLeeKonnor** [comment]
I've never ripped anything. Therefore, it's completely slanderous. Your
"mod" went from entirely cool to completely malicious when you started
painting targets on people YOU DONT EVEN KNOW.
I knew Requi and he used to be a good person.

**Comment by RequiDev** [comment]
You knew me? I don't know who you are.
All I can tell you is that this specific mod has no such functionality.

**Comment by Kiokuu** [comment]
ReModCE does not contain any feature that matches your description of creating a list of "A list of people suspected of ripping..."
I'd also like to mention it seems strange you mention the fact that you have "never ripped anything" and are attempting to defend yourself against something that doesn't exist in ReModCE.

**Comment by loukylor** [comment]
If you can provide evidence of this feature existing then by all means reopen this issue. However, for now, I will close this issue.
